# Generated by Django 5.2 on 2025-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0012_member_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_last_shown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
