# Generated by Django 5.2 on 2025-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_attendance_event_member_delete_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='member_avatars/'),
        ),
    ]
