# Generated by Django 5.2 on 2025-05-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0007_member_qr_code_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='section',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
