# Generated by Django 5.2 on 2025-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0011_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
