# Generated by Django 5.2 on 2025-05-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0013_member_password_last_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password_last_shown',
        ),
        migrations.AddField(
            model_name='member',
            name='password_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='temp_password',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
