# Generated by Django 5.2 on 2025-05-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0015_event_end_time_event_start_time'),
        ('eqrApp', '0016_populate_event_times'),
    ]

    operations = [
    ]
