# Generated by Django 5.2 on 2025-05-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0017_merge_20250508_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqrApp.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqrApp.member')),
            ],
            options={
                'unique_together': {('member', 'event')},
            },
        ),
    ]
