# Generated by Django 4.2.21 on 2025-05-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0020_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='image',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='encrypted_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
