# Generated by Django 4.2.21 on 2025-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0021_remove_qrcode_image_qrcode_encrypted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='temp_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
